### ISSUE TITLE
[Bug]: Player without the mod gets kicked from server with mod when Ender Chest with Shulker Box(es)  is opened

### ISSUE THREAD

**Issue by AstudilloMarillo** [Fuzss/easyshulkerboxes#46]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

20.4.1

### Minimal Setup (Required)

Yes

### Notes (Required)

Any player without the mod gets kicked from a server that has the Easy Shulker Boxes mod installed when opening an Ender Chest with Shulker Box(es) inside. I believe any player not running the mod should be able to use their Ender Chests and Shulker Boxes as normal right?

This is the log from the console:

[11:59:08] [Server thread/WARN]: Failed to handle packet for /[ip address obfuscated]
net.minecraft.class_148: Ticking player
at net.minecraft.class_3222.method_14226(class_3222.java:583) ~[server-intermediary.jar:?]
at net.minecraft.class_3244.method_18784(class_3244.java:257) ~[server-intermediary.jar:?]
at net.minecraft.class_2535.method_10754(class_2535.java:379) ~[server-intermediary.jar:?]
at net.minecraft.class_3242.method_14357(class_3242.java:176) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:959) ~[server-intermediary.jar:?]
at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1703.method_7623()" because the return value of "fuzs.iteminteractions.impl.capability.EnderChestMenuCapability.getEnderChestMenu()" is null
at fuzs.iteminteractions.impl.handler.EnderChestMenuHandler.onStartPlayerTick(EnderChestMenuHandler.java:16) ~[iteminteractions-20.4.1-ad64501956697dc6.jar:?]
at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
at fuzs.puzzleslib.fabric.api.event.v1.core.FabricEventFactory.invokeFast(FabricEventFactory.java:152) ~[PuzzlesLib-v20.4.36-1.20.4-Fabric.jar:?]
at fuzs.puzzleslib.fabric.api.event.v1.core.FabricEventFactory$1.handleInvocation(FabricEventFactory.java:38) ~[PuzzlesLib-v20.4.36-1.20.4-Fabric.jar:?]
at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[guava-32.1.2-jre.jar:?]
at jdk.proxy2.$Proxy41.onStartPlayerTick(Unknown Source) ~[?:?]
at net.minecraft.class_1657.handler$bhl000$puzzleslib$tick$0(class_1657.java:3343) ~[server-intermediary.jar:?]
at net.minecraft.class_1657.method_5773(class_1657.java) ~[server-intermediary.jar:?]
at net.minecraft.class_3222.method_14226(class_3222.java:519) ~[server-intermediary.jar:?]
... 9 more
[11:59:08] [Server thread/INFO]: PlayerName lost connection: Internal server error

### latest.log (Required)

console log posted above

**Comment by Fuzss** [comment]
Easy Shulker Boxes is not optional client-side. If you have it on your server clients must install it as well.
Fabric unfortunately has no way to enforce this, so that's why it's possible to join the server without the mod.
The mod page has installation instructions where you will find where a mod needs to be installed to work properly.

**Comment by AstudilloMarillo** [comment]
That does explain it. Are you unable to make it optional for client-side? Not all my friends like to play with mods.

**Comment by Fuzss** [comment]
The problematic part of the implementation has changed in the most recent version, maybe it will work now for your players that don't have the mod.

Intentionally making the mod optional on clients isn't something I'm otherwise interested in.

**Comment by AstudilloMarillo** [comment]
> The problematic part of the implementation has changed in the most recent version, maybe it will work now for your players that don't have the mod.

Just tested it with a friend and it does actually work with the newest version! So for now that's great, hope it stays in the future, but I understand it's not a priority for you. Thanks anyway :)
